/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 import java.sql.*;
 import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author varun
 */
public class SignUpInfo extends javax.swing.JFrame {

      String AccNo1,password1, email1,AccountType,name1;
      
    /**
     * Creates new form SignUpInfo
     */
    public SignUpInfo() {
        initComponents();
    }
    public SignUpInfo(String AccNo, String password , String email,String accountType){
        AccNo1=AccNo;
        password1=password;
        email1=email;
        AccountType=accountType;
       
        initComponents();
        //getContentPane().setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        nominee = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        nextButton = new javax.swing.JButton();
        nomineeRelation = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        LMaritalStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setText("   Personal Info.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("FatherName");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Nominee");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Marital Status");

        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 111, 201), 2, true));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 111, 201), 2, true));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        fatherName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 111, 201), 2, true));
        fatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNameActionPerformed(evt);
            }
        });

        nominee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 111, 201), 2, true));
        nominee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomineeActionPerformed(evt);
            }
        });

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        nextButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        nomineeRelation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomineeRelation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Husband", "Wife", "Father", "Mother", "Brother", "Sister ", "Others", " " }));
        nomineeRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomineeRelationActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Relation with Nominee ");

        LMaritalStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married", "Unmarried", " " }));
        LMaritalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LMaritalStatusActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-back-arrow.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LMaritalStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nominee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fatherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(314, 314, 314))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nomineeRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(378, 378, 378))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(498, 498, 498)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(618, 618, 618)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(LMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nominee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomineeRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(nextButton)
                            .addGap(95, 95, 95))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:

            String str=name.getText();
          
            System.out.println(str);
           int s=str.length();
           char ch;
           boolean wrong=false;           
           for(int i=0;i<s;++i ){
             ch=str.charAt(i);
             
             if(Character.isDigit(ch)) {
               wrong=true;
                break;
         
             } 
             else {
                  }
           }
                 if(wrong)
                 {
                        JOptionPane.showMessageDialog(null,"NO NUMERIC VALUES Allowed","Alert",JOptionPane.WARNING_MESSAGE);     
       
                     name.setText("");
                   
                      }
            
        // TODO add your handling code here:

    }//GEN-LAST:event_nameActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
    if("".equals(name.getText())){
        System.out.println("Enter Name\n");
      JOptionPane.showMessageDialog(null,"Name cannot be left empty","",JOptionPane.WARNING_MESSAGE);     
     //    return;
     
        return;
    }
    if("".equals(age.getText())){
       // System.out.println("Enter Age\n");
        JOptionPane.showMessageDialog(null,"Age cannot be left empty","",JOptionPane.WARNING_MESSAGE);     
       //  return;
      
       return;
    }
    if("".equals(fatherName.getText())){
        System.out.println("Enter Name\n");
       JOptionPane.showMessageDialog(null,"FatherName cannot be left empty","",JOptionPane.WARNING_MESSAGE);     
         return;
     
//        return;
    }
    
    //if(maritalStatus.getText()==""){
   //     System.out.println("Enter Name\n");
    //    return;
    //}
    
    
    if("".equals(nominee.getText())){
        JOptionPane.showMessageDialog(null,"Nominee cannot be left empty","",JOptionPane.WARNING_MESSAGE);     
        // return;
     
        System.out.println("Enter Nominee\n");
        return;
    }
    if("".equals(address.getText()))
    {
        System.out.println("Address can not be Empty\n");
    JOptionPane.showMessageDialog(null,"Address cannt be left empty","",JOptionPane.WARNING_MESSAGE);     
        // return;
     
        return ;
    }
    try{
        name1=name.getText();
     String query=  "insert into users values('"+AccNo1+"','"+password1+"','"+AccountType+"','"+name1+"');";

        MakeConnection c=new MakeConnection(query);
  //String query="insert into users values(' "
  int pp1= c.s.executeUpdate(query);
  //  cl.s.close();
   // c.s.close();

  String query1=  "insert into userdetail values('"+AccNo1+"','"+name.getText()+"','"+age.getText()+"','"+fatherName.getText()+"','"+LMaritalStatus.getSelectedItem().toString()+"','"+nominee.getText()+"','"+nomineeRelation.getSelectedItem().toString()+"','"+address.getText()+"',"+0.0+");";
      
     int a=c.s.executeUpdate(query1);
     c.s.close();
         ImageIcon ic= new ImageIcon("C:\\Users\\varun\\Downloads\\like.png");
         JOptionPane.showMessageDialog(null,"Account Created Successfully.","Status",JOptionPane.WARNING_MESSAGE,ic);     
         
// JOptionPane.showMessageDialog(null,"Congrats, Account Created","Account Status",JOptionPane.WARNING_MESSAGE,);     
   
    }
    catch(SQLException e){
   JOptionPane.showMessageDialog(null,"Error,Account  Not Created\n"+e.getMessage(),"Account Status",JOptionPane.WARNING_MESSAGE);        
    
        System.out.println(e);
    }
    catch(Exception e){
   JOptionPane.showMessageDialog(null,"Error, Account NOt Created\n"+e.getMessage(),"Account Status",JOptionPane.WARNING_MESSAGE);     
   
        System.out.println(e);
        
    }
    setVisible(false);
   
    
        // TODO add your handling code here:
    
    }//GEN-LAST:event_nextButtonActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
        
                  String str=age.getText();
          
            System.out.println(str);
           int s=str.length();
           char ch;
           boolean wrong=false;           
           for(int i=0;i<s;++i ){
             ch=str.charAt(i);
             
             //if(Character.isDigit(ch)) {
              
             if(ch>=48 && ch<=58 ) {
             
             } 
             else {
                 wrong=true;
                break;
           }
           }
                 if(wrong)
                 {
                        JOptionPane.showMessageDialog(null,"Kindly Enter only NUMERIC VALUES","Alert",JOptionPane.WARNING_MESSAGE);     
       
                     age.setText("");
                   
                      }
            
        // TODO add your handling code here:

    }//GEN-LAST:event_ageActionPerformed

    private void nomineeRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomineeRelationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomineeRelationActionPerformed

    private void LMaritalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LMaritalStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LMaritalStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     dispose();
     SignUp s=new SignUp();
     s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNameActionPerformed
        // TODO add your handling code here:

            String str=fatherName.getText();
          
            System.out.println(str);
           int s=str.length();
           char ch;
           boolean wrong=false;           
           for(int i=0;i<s;++i ){
             ch=str.charAt(i);
             
  //           if(Character.isDigit(ch)) {
    
    if(ch>=65 && ch<=90  || ch >=97 && ch<=120 || ch==32) {
             
  
             } 
             else {
                 wrong=true;
                break;
           }
           }
                 if(wrong)
                 {
                        JOptionPane.showMessageDialog(null,"No Numeric  VALUES Allowed","Alert",JOptionPane.WARNING_MESSAGE);     
       
                     fatherName.setText("");
                   
                      }
            
        // TODO add your handling code here:


    }//GEN-LAST:event_fatherNameActionPerformed

    private void nomineeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomineeActionPerformed
        // TODO add your handling code here:
        
                  String str=nominee.getText();
          
            System.out.println(str);
           int s=str.length();
           char ch;
           boolean wrong=false;           
           for(int i=0;i<s;++i ){
             ch=str.charAt(i);
             
             if(ch>=65 && ch<=90  || ch >=97 && ch<=120 || ch==32) {
                
             } 
             else {
                 wrong=true;
                break;
           }
           }
                 if(wrong)
                 {
                        JOptionPane.showMessageDialog(null,"No NUMERIC VALUES","Alert",JOptionPane.WARNING_MESSAGE);     
       
                     nominee.setText("");
                   
                      }
            
        // TODO add your handling code here:

    }//GEN-LAST:event_nomineeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               SignUpInfo sf=new SignUpInfo();
               sf.setVisible(true);
                  
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LMaritalStatus;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField fatherName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField nominee;
    private javax.swing.JComboBox<String> nomineeRelation;
    // End of variables declaration//GEN-END:variables
}
